apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-name
  namespace: {{ .Values.Namespacename }}
spec:
  hard:
    requests.cpu: '1'
    requests.memory: 1Gi
    limits.cpu: '1'
    limits.memory: 1Gi
    pods: '3'